### ISSUE TITLE
Is there a forum for sharing ideas/tools/code?

### ISSUE THREAD

**Issue by cristoslc** [hackforwesternmass/hackforwesternma-docs#32]
Based on another site I'm building, I put together a simple web page template that pulls data from a published Google Spreadsheet (https://github.com/cristoslc/sts-template). You can change the spreadsheet in one line of code, and the rest is drop-in HTML, CSS, and JavaScript files.

I thought it might be useful for anyone who wants to quickly prototype a web page during the challenge. Is there a forum in which this kind of information should be posted?

**Comment by a-pasquale** [comment]
That looks like it could be useful for a lot of projects.  We are using Hackpad as a wiki-like collaboration tool.  I'd suggest posting there.  The high level page is https://hackforchange.hackpad.com/HACK-FOR-WESTERN-MASS-2014-1ZyQneaq3Wp

You might post on specific challenge pages that you think this would benefit or maybe on the page listing the challenges?  Or we could create a new "Resources" page?

**Comment by cristoslc** [comment]
I think it would be handy to have a "Resources" page that folks could contribute to. You never know exactly what someone else will find useful, and it would add a lot of noise (and be redundant) to have the same ones repeated on multiple project pages.

**Comment by a-pasquale** [comment]
I created a hackpad for sharing resources here: https://hackforchange.hackpad.com/Resources-pxWZLxI5oQc

**Comment by cristoslc** [comment]
Outstanding!

Psyched for tomorrow. See you guys there!
